apiVersion: perses.dev/v1alpha1
kind: PersesDatasource
metadata:
  name: uwm-thanos
  namespace: observability-demo
spec:
  config:
    default: true
    display:
      name: "Platform Thanos"
    plugin:
      kind: "PrometheusDatasource"
      spec:
        proxy:
          kind: "HTTPProxy"
          spec:
            url: "https://thanos-querier.openshift-monitoring.svc:9091"
            secret: thanos-auth
            allowedEndpoints:
              - endpointPattern: "/api/v1/labels"
                method: "POST"
              - endpointPattern: "/api/v1/series"
                method: "POST"
              - endpointPattern: "/api/v1/metadata"
                method: "GET"
              - endpointPattern: "/api/v1/query"
                method: "POST"
              - endpointPattern: "/api/v1/query"
                method: "GET"
              - endpointPattern: "/api/v1/query_range"
                method: "POST"
              - endpointPattern: "/api/v1/query_range"
                method: "GET"
              - endpointPattern: "/api/v1/label/([a-zA-Z0-9_-]+)/values"
                method: "GET"
---
apiVersion: perses.dev/v1alpha1
kind: PersesDashboard
metadata:
  name: hybrid-cloud-demo
  namespace: observability-demo
spec:
  duration: "30m"
  display:
    name: "Workload Details (Hybrid Cloud)"

  variables:
    - kind: "ListVariable"
      spec:
        name: "service"
        display: { name: "Service" }
        plugin:
          kind: "PrometheusLabelValuesVariable"
          spec:
            datasource: { kind: "PrometheusDatasource", name: "uwm-thanos" }
            labelName: "service_name"
            matchers:
              ["jvm_memory_used_bytes{k8s_namespace_name='observability-demo'}"]

    - kind: "ListVariable"
      spec:
        name: "pod"
        display: { name: "Pod" }
        plugin:
          kind: "PrometheusLabelValuesVariable"
          spec:
            datasource: { kind: "PrometheusDatasource", name: "uwm-thanos" }
            labelName: "k8s_pod_name"
            matchers: ["jvm_memory_used_bytes{service_name='$service'}"]

  layouts:
    # - kind: "Grid"
    #   spec:
    #     display: { title: "Business KPIs", collapse: { open: true } }
    #     items:
    #       - x: 0
    #         y: 0
    #         width: 12 
    #         height: 6
    #         content: { "$ref": "#/spec/panels/businessCounter" }
    - kind: "Grid"
      spec:
        display: { title: "Application Health", collapse: { open: true } }
        items:
          - x: 0
            y: 0
            width: 8
            height: 6
            content: { "$ref": "#/spec/panels/reqRate" }
          - x: 8
            y: 0
            width: 8
            height: 6
            content: { "$ref": "#/spec/panels/reqLatency" }
          - x: 16
            y: 0
            width: 8
            height: 6
            content: { "$ref": "#/spec/panels/reqErrors" }

    - kind: "Grid"
      spec:
        display: { title: "Infrastructure (Pod/VM)", collapse: { open: true } }
        items:
          - x: 0
            y: 0
            width: 8
            height: 6
            content: { "$ref": "#/spec/panels/infraCpu" }
          - x: 8
            y: 0
            width: 8
            height: 6
            content: { "$ref": "#/spec/panels/infraMem" }
          - x: 16
            y: 0
            width: 8
            height: 6
            content: { "$ref": "#/spec/panels/infraNet" }

    - kind: "Grid"
      spec:
        display: { title: "JVM Runtime", collapse: { open: true } }
        items:
          - x: 0
            y: 0
            width: 8
            height: 6
            content: { "$ref": "#/spec/panels/jvmHeap" }
          - x: 8
            y: 0
            width: 8
            height: 6
            content: { "$ref": "#/spec/panels/jvmGC" }
          - x: 16
            y: 0
            width: 8
            height: 6
            content: { "$ref": "#/spec/panels/jvmThreads" }

  panels:
    # businessCounter:
    #   kind: "Panel"
    #   spec:
    #     display: { name: "Business Transaction Count", description: "Custom metric from code" }
    #     plugin:
    #       kind: "TimeSeriesChart"
    #       spec:
    #         legend: { position: "bottom" }
    #         y_axis:
    #           unit:
    #             kind: "Decimal"
    #     queries:
    #       - kind: "TimeSeriesQuery"
    #         spec:
    #           plugin:
    #             kind: "PrometheusTimeSeriesQuery"
    #             spec:
    #               datasource: { kind: "PrometheusDatasource", name: "uwm-thanos" }
    #               query: "sum by (job) (rate(business_sales_total_count{service_name+'$service'}[1m]))"
    reqRate:
      kind: "Panel"
      spec:
        display: { name: "Request Rate", description: "RPS" }
        plugin:
          kind: "TimeSeriesChart"
          spec:
            yAxis:
              format: 
                unit: "requests/sec"
            legend: { position: "bottom" }
        queries:
          - kind: "TimeSeriesQuery"
            spec:
              plugin:
                kind: "PrometheusTimeSeriesQuery"
                spec:
                  datasource: { kind: "PrometheusDatasource", name: "uwm-thanos" }
                  query: "sum by (k8s_pod_name) (rate(http_server_request_duration_seconds_count{service_name='$service'}[1m]))"

    reqLatency:
      kind: "Panel"
      spec:
        display: { name: "Latency (p95)", description: "95th Percentile" }
        plugin:
          kind: "TimeSeriesChart"
          spec:
            yAxis:
              format: 
                unit: "seconds"
                decimalPlaces: 2
            legend: { position: "bottom" }
        queries:
          - kind: "TimeSeriesQuery"
            spec:
              plugin:
                kind: "PrometheusTimeSeriesQuery"
                spec:
                  datasource: { kind: "PrometheusDatasource", name: "uwm-thanos" }
                  query: "histogram_quantile(0.95, sum by (le,k8s_pod_name) (rate(http_server_request_duration_seconds_bucket{service_name='$service', k8s_pod_name=~'$pod'}[1m])))"

    reqErrors:
      kind: "Panel"
      spec:
        display: { name: "Error Rate (%)", description: "Percentage of failed requests" }
        plugin:
          kind: "TimeSeriesChart"
          spec:
            visual: { palette: { mode: "auto" } }
            legend: { position: "bottom" }
            yAxis:
              format: 
                unit: "percent"
                decimalPlaces: 2
        queries:
          - kind: "TimeSeriesQuery"
            spec:
              plugin:
                kind: "PrometheusTimeSeriesQuery"
                spec:
                  datasource: { kind: "PrometheusDatasource", name: "uwm-thanos" }
                  query: "(sum by (k8s_pod_name)(rate(http_server_request_duration_seconds_count{service_name='$service', k8s_pod_name=~'$pod', http_response_status_code=~'5.*'}[1m])) / sum by (k8s_pod_name)(rate(http_server_request_duration_seconds_count{service_name='$service', k8s_pod_name=~'$pod'}[1m]))) * 100" 
    
    infraCpu:
      kind: "Panel"
      spec:
        display: { name: "Pod CPU Usage (Avg 1m)" }
        plugin:
          kind: "TimeSeriesChart"
          spec:
            legend: { position: "bottom" }
            yAxis:
              format: 
                unit: "decimal"
                decimalPlaces: 2
        queries:
          - kind: "TimeSeriesQuery"
            spec:
              plugin:
                kind: "PrometheusTimeSeriesQuery"
                spec:
                  datasource: { kind: "PrometheusDatasource", name: "uwm-thanos" }
                  query: "sum by (k8s_pod_name) (avg_over_time(k8s_pod_cpu_usage{job='observability-demo/otel-infra-collector-monitor', k8s_pod_name=~'$pod'}[1m]))"

    infraMem:
      kind: "Panel"
      spec:
        display: { name: "Pod Memory (Avg 1m)" }
        plugin:
          kind: "TimeSeriesChart"
          spec:
            legend: { position: "bottom" }
            yAxis:
              format: 
                unit: "bytes"
                decimalPlaces: 2
        queries:
          - kind: "TimeSeriesQuery"
            spec:
              plugin:
                kind: "PrometheusTimeSeriesQuery"
                spec:
                  datasource: { kind: "PrometheusDatasource", name: "uwm-thanos" }
                  query: "sum by (k8s_pod_name) (avg_over_time(k8s_pod_memory_working_set_bytes{job='observability-demo/otel-infra-collector-monitor', k8s_pod_name=~'$pod'}[1m]))"

    infraNet:
      kind: "Panel"
      spec:
        display: { name: "Network I/O" }
        plugin:
          kind: "TimeSeriesChart"
          spec:
            legend: { position: "bottom" }
            yAxis:
              format: 
                unit: "bytes"
                decimalPlaces: 2
        queries:
          - kind: "TimeSeriesQuery"
            spec:
              plugin:
                kind: "PrometheusTimeSeriesQuery"
                spec:
                  datasource: { kind: "PrometheusDatasource", name: "uwm-thanos" }
                  query: "sum by (job, k8s_pod_name) (rate(k8s_pod_network_io_bytes_total{job='observability-demo/otel-infra-collector-monitor', k8s_pod_name=~'$pod', direction='receive'}[1m]))"
                  seriesNameFormat: "RX {{k8s_pod_name}}"
          - kind: "TimeSeriesQuery"
            spec:
              plugin:
                kind: "PrometheusTimeSeriesQuery"
                spec:
                  datasource: { kind: "PrometheusDatasource", name: "uwm-thanos" }
                  query: "sum by (job, k8s_pod_name) (rate(k8s_pod_network_io_bytes_total{job='observability-demo/otel-infra-collector-monitor', k8s_pod_name=~'$pod', direction='transmit'}[1m]))"
                  seriesNameFormat: "TX {{k8s_pod_name}}"

    jvmHeap:
      kind: "Panel"
      spec:
        display: { name: "JVM Heap Usage (Avg 1m)" }
        plugin:
          kind: "TimeSeriesChart"
          spec:
            legend: { position: "bottom" }
            yAxis:
              format: 
                unit: "bytes"
                decimalPlaces: 2
        queries:
          - kind: "TimeSeriesQuery"
            spec:
              plugin:
                kind: "PrometheusTimeSeriesQuery"
                spec:
                  datasource: { kind: "PrometheusDatasource", name: "uwm-thanos" }
                  query: "sum by (jvm_memory_pool_name) (avg_over_time(jvm_memory_used_bytes{service_name='$service', k8s_pod_name=~'$pod', jvm_memory_type='heap'}[1m]))"

    jvmGC:
      kind: "Panel"
      spec:
        display: { name: "GC Duration" }
        plugin:
          kind: "TimeSeriesChart"
          spec:
            legend: { position: "bottom" }
            yAxis:
              format: 
                unit: "decimal"
        queries:
          - kind: "TimeSeriesQuery"
            spec:
              plugin:
                kind: "PrometheusTimeSeriesQuery"
                spec:
                  datasource: { kind: "PrometheusDatasource", name: "uwm-thanos" }
                  query: "sum by(k8s_pod_name)(rate(jvm_gc_duration_seconds_sum{service_name='$service', k8s_pod_name=~'$pod'}[1m]))"

    jvmThreads:
      kind: "Panel"
      spec:
        display: { name: "Thread Count" }
        plugin:
          kind: "TimeSeriesChart"
          spec: 
            legend: { position: "bottom" }
            yAxis:
              format: 
                unit: "decimal"
        queries:
          - kind: "TimeSeriesQuery"
            spec:
              plugin:
                kind: "PrometheusTimeSeriesQuery"
                spec:
                  datasource: { kind: "PrometheusDatasource", name: "uwm-thanos" }
                  query: "sum by(k8s_pod_name)(max_over_time(jvm_thread_count{service_name='$service', k8s_pod_name=~'$pod'}[1m]))"