apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: openshift-netobserv-operator
  labels:
    openshift.io/cluster-monitoring: "true"
    kubernetes.io/metadata.name: openshift-netobserv-operator
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: netobserv
  labels:
    openshift.io/cluster-monitoring: "true"
    kubernetes.io/metadata.name: netobserv