# ========================================================
# 1. QUARKUS BACKEND
# ========================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-backend
  namespace: observability-demo
  labels:
    app: quarkus-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-backend
  template:
    metadata:
      labels:
        app: quarkus-backend
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: quarkus
          image: ghcr.io/too-common-name/observability-demo/quarkus-backend:v0.0.1
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-backend
  namespace: observability-demo
spec:
  selector:
    app: quarkus-backend
  ports:
    - port: 8080
      targetPort: 8081
---
# ========================================================
# 2. TOMCAT FRONTEND (Virtual Machine)
# ========================================================
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: frontend-tomcat-vm
  namespace: observability-demo
  labels:
    app: frontend-tomcat-service
    vm.kubevirt.io/name: frontend-tomcat-service
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        app: frontend-tomcat-service
        vm.kubevirt.io/name: frontend-tomcat-service
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: fedora
              password: fedora
              chpasswd: { expire: False }

              packages:
                - java-25-openjdk
                - wget
                - tar

              runcmd:
                - useradd -r -m -U -d /opt/tomcat -s /bin/false tomcat

                - wget https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.19/bin/apache-tomcat-10.1.19.tar.gz -O /tmp/tomcat.tar.gz
                - mkdir -p /opt/tomcat
                - tar xzf /tmp/tomcat.tar.gz -C /opt/tomcat --strip-components=1
                
                - wget https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar -O /opt/tomcat/lib/opentelemetry-javaagent.jar
                
                - |
                  cat <<EOF > /opt/tomcat/bin/setenv.sh
                  #!/bin/sh
                  export QUARKUS_BACKEND_URL="http://quarkus-backend.observability-demo.svc.cluster.local:8080"
                  export OTEL_EXPORTER_OTLP_ENDPOINT="http://otel-app-collector.observability-demo.svc.cluster.local:4317"
                  export OTEL_EXPORTER_OTLP_PROTOCOL="grpc"
                  export OTEL_METRIC_EXPORT_INTERVAL="15000"
                  export OTEL_METRICS_EXPORTER="otlp"
                  export OTEL_SERVICE_NAME="frontend-tomcat-vm"
                  export CATALINA_OPTS="$CATALINA_OPTS -javaagent:/opt/tomcat/lib/opentelemetry-javaagent.jar"
                  EOF
                - chmod +x /opt/tomcat/bin/setenv.sh
                
                - rm -rf /opt/tomcat/webapps/ROOT
                - wget https://github.com/too-common-name/observability-demo/releases/download/v0.0.1/ROOT.war -O /opt/tomcat/webapps/ROOT.war

                - chown -R tomcat:tomcat /opt/tomcat
                - chmod +x /opt/tomcat/bin/*.sh
                - chcon -R -t bin_t /opt/tomcat/bin
                - chcon -R -t usr_t /opt/tomcat/lib
                - chcon -R -t usr_t /opt/tomcat/webapps

                - |
                  cat <<EOF > /etc/systemd/system/tomcat.service
                  [Unit]
                  Description=Apache Tomcat
                  After=network.target syslog.target
                  [Service]
                  User=tomcat
                  Group=tomcat
                  Type=oneshot
                  ExecStart=/opt/tomcat/bin/startup.sh
                  ExecStop=/opt/tomcat/bin/shutdown.sh
                  RemainAfterExit=yes
                  [Install]
                  WantedBy=multi-user.target
                  EOF

                - systemctl daemon-reload
                - systemctl enable --now tomcat
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-tomcat-service
  namespace: observability-demo
spec:
  selector:
    app: frontend-tomcat-service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend-tomcat-service
  namespace: observability-demo
spec:
  to:
    kind: Service
    name: frontend-tomcat-service
  port:
    targetPort: 8080
  tls:
    termination: edge