apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-error-alerts
  namespace: observability-demo
  labels:
    role: alert-rules
spec:
  groups:
  - name: application-slo.rules
    rules:
    - alert: HighErrorRate
      expr: |
        (
          sum by (service_name, namespace) (rate(http_server_request_duration_seconds_count{http_response_status_code=~"5.*"}[1m])) 
          / 
          sum by (service_name, namespace) (rate(http_server_request_duration_seconds_count[1m]))
        ) * 100 > 60
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "High Error Rate detected for {{ $labels.service_name }}"
        description: "The service {{ $labels.service_name }} in namespace {{ $labels.k8s_namespace_name }} is failing {{ $value | humanize }}% of requests (Threshold: 65%)."