apiVersion: tempo.grafana.com/v1alpha1
kind:  TempoStack
metadata:
  name: demo-tempostack
  namespace: observability-demo-backend
spec:
  storage:
    secret:
      name: observability-demo-tempo-secret
      type: s3
  storageSize: 1Gi
  resources:
    total:
      limits:
        memory: 4Gi
        cpu: 2000m
  tenants:
    mode: openshift
    authentication:
      - tenantName: demo
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfa"
      - tenantName: dev
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfb"
      - tenantName: prod
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfc"
  template:
    gateway:
      enabled: true
      rbac:
        enabled: true 