# ========================================================
# 1. TEMPO GLOBAL READER (For OCP Console Users)
# ========================================================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-reader
rules:
  - apiGroups:
      - 'tempo.grafana.com'
    resources:
      - platform
      - demo
      - dev
      - prod
    resourceNames:
      - traces
    verbs:
      - 'get' 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempostack-traces-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempostack-traces-reader
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated 

---
# ========================================================
# 2. APP COLLECTOR: Service Account & Discovery RBAC
# ========================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-app-collector-deployment
  namespace: observability-demo-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: otel-app-discovery-role
  namespace: observability-example
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes", "endpoints", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachineinstances"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: otel-app-discovery-binding
  namespace: observability-example
subjects:
- kind: ServiceAccount
  name: otel-app-collector-deployment
  namespace: observability-demo-backend
roleRef:
  kind: Role
  name: otel-app-discovery-role
  apiGroup: rbac.authorization.k8s.io

---
# ========================================================
# 3. APP COLLECTOR: Tempo Write RBAC
# ========================================================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-write-rbac
rules:
  - apiGroups:
      - 'tempo.grafana.com'
    resources:
      - platform
      - demo
      - dev
      - prod
    resourceNames:
      - traces
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempostack-traces-write-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempostack-traces-write-rbac
subjects:
  - kind: ServiceAccount
    name: otel-app-collector-deployment
    namespace: observability-demo-backend

---
# ========================================================
# 4. APP COLLECTOR: Loki Logs Write Access
# ========================================================
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logging-collector-logs-writer 
rules:
- apiGroups:
  - loki.grafana.com
  resourceNames:
  - logs
  resources:
  - application
  - audit
  - infrastructure
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-app-collector-logs-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-collector-logs-writer
subjects:
  - kind: ServiceAccount
    name: otel-app-collector-deployment
    namespace: observability-demo-backend
---
# ========================================================
# 5. INFRA COLLECTOR: SA & Full Access RBAC
# ========================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-infra-collector-deployment
  namespace: observability-demo-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-infra-collector-full-access
rules:
# 1. KUBELET SCRAPING
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "nodes/metrics", "nodes/stats"]
  verbs: ["get", "list", "watch"]
# 2. K8S ATTRIBUTES ENRICHMENT
- apiGroups: [""]
  resources: ["pods", "namespaces", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
# 3. DEPLOYMENT & VMI CORRELATION
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachineinstances", "virtualmachineinstances/status"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-infra-collector-full-binding
subjects:
- kind: ServiceAccount
  name: otel-infra-collector-deployment
  namespace: observability-demo-backend
roleRef:
  kind: ClusterRole
  name: otel-infra-collector-full-access
  apiGroup: rbac.authorization.k8s.io