apiVersion: v1
kind: Secret
metadata:
  name: observability-demo-loki-secret
  namespace: openshift-logging
type: Opaque
stringData:
  bucket: ""
  bucketnames: https://s3.openshift-storage.svc
  access_key_id: ""
  access_key_secret: ""