apiVersion: v1
kind: Secret
metadata:
  name: observability-demo-tempo-secret
  namespace: openshift-tracing
type: Opaque
stringData:
  bucket: ""
  endpoint: https://s3.openshift-storage.svc
  access_key_id: ""
  access_key_secret: ""